//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SelfBeautifyingPainting.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SelfBeautifyingPainting.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;!--
        ///    Stump-based 24x24 discrete(?) adaboost frontal face detector.
        ///    Created by Rainer Lienhart.
        ///
        ///////////////////////////////////////////////////////////////////////////////////////////
        ///
        ///  IMPORTANT: READ BEFORE DOWNLOADING, COPYING, INSTALLING OR USING.
        ///
        ///  By downloading, copying, installing or using the software you agree to this license.
        ///  If you do not agree to this license, do not download, install,
        ///  copy or use the software.
        ///
        ///
        ///                        Intel License Agreeme [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FaceCascade {
            get {
                return ResourceManager.GetString("FaceCascade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;!----------------------------------------------------------------------------
        ///  Smile detector
        ///  Contributed by Oscar Deniz Suarez
        ///  More information can be found at http://visilab.etsii.uclm.es/personas/oscar/oscar.html
        ///  
        /////////////////////////////////////////////////////////////////////////////
        ///| Contributors License Agreement
        ///| IMPORTANT: READ BEFORE DOWNLOADING, COPYING, INSTALLING OR USING.
        ///|   By downloading, copying, installing or using the software you agree 
        ///|   to [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MouthCascade {
            get {
                return ResourceManager.GetString("MouthCascade", resourceCulture);
            }
        }
    }
}
